version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image: application:latest
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - LOGGING_LEVEL_ORG_HIBERNATE_TYPE=trace
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=debug
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true



  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres