#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
security:
  properties:
    tokenSecret: gre32regeh3
    expirationTime: 864000000
    tokenPrefix: 'Bearer '
    headerString: Authorization
    signUpUrl: /users
    h2ConsoleUrl: /h2-console/**
    loginUrl: /users/login